services:
  zookeeper:
    image: bitnami/zookeeper:3.9.2
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    restart: unless-stopped

  redis:
    image: redis:6.0.16
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    restart: unless-stopped

  mysql:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: myself_chatroom
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ./server/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  chatroom-app:
    build: ./server
    container_name: chatroom-app
    ports:
      - "8080:8080"
      - "8090:8090"
      - "50051:50051"
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER: kafka:9092
      ZK_ADDR: zookeeper:2181
      REDIS_ADDR: redis:6379
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_USER: root
      MYSQL_PASS: "123"
    restart: unless-stopped

  web-frontend:
    build: ./client/web
    container_name: web-frontend
    ports:
      - "80:80"
    environment:
      TZ: Asia/Shanghai
      SERVER_BASE_URL: http://chatroom-app:8080
    restart: unless-stopped